/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectointegrador_fase2;

/**
 *
 * @author nathalyparedes
 */
public class Empezar extends javax.swing.JFrame {

    /**
     * Creates new form Empezar
     */
    public Empezar() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButtonFacil = new javax.swing.JButton();
        jButtonIntermedio = new javax.swing.JButton();
        jButtonDificil = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("NOMBRE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("APELLIDO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 170, 40));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 170, 40));

        jButtonFacil.setBackground(new java.awt.Color(102, 51, 0));
        jButtonFacil.setFont(new java.awt.Font("October Condensed Devanagari", 0, 24)); // NOI18N
        jButtonFacil.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFacil.setText("FÁCIL");
        jButtonFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFacilActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 160, 50));

        jButtonIntermedio.setBackground(new java.awt.Color(102, 51, 0));
        jButtonIntermedio.setFont(new java.awt.Font("October Condensed Tamil", 0, 24)); // NOI18N
        jButtonIntermedio.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIntermedio.setText("INTERMEDIO");
        jButtonIntermedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIntermedioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIntermedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 160, 50));

        jButtonDificil.setBackground(new java.awt.Color(102, 51, 0));
        jButtonDificil.setFont(new java.awt.Font("October Condensed Tamil", 0, 24)); // NOI18N
        jButtonDificil.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDificil.setText("DIFÍCIL");
        jButtonDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDificilActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 160, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/nathalyparedes/Downloads/Poo/EcoMinful copy.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 530, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/nathalyparedes/Downloads/Poo/Juego_ventana.jpg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFacilActionPerformed
        // TODO add your handling code here:
        Juego frmjuego = new Juego ();
        frmjuego.setVisible(true);
        frmjuego.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonFacilActionPerformed

    private void jButtonIntermedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIntermedioActionPerformed
        // TODO add your handling code here:
        Juego frmjuego = new Juego ();
        frmjuego.setVisible(true);
        frmjuego.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonIntermedioActionPerformed

    private void jButtonDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDificilActionPerformed
        // TODO add your handling code here:
        Juego frmjuego = new Juego ();
        frmjuego.setVisible(true);
        frmjuego.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonDificilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empezar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empezar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empezar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empezar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empezar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDificil;
    private javax.swing.JButton jButtonFacil;
    private javax.swing.JButton jButtonIntermedio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
